services:
  - type: web
    name: niletechno-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_HOSTBUILDER_RELOADCONFIGONCHANGE
        value: "false"
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
